name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ci_test
        ports:
          - 3306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        include:
          # Laravel 10
          - os: ubuntu-latest
            php: 8.1
            laravel: 10.*
            livewire: ^3.0
            testbench: 8.*
            carbon: ^2.63
            pest: ^2.0
            pest-plugin-laravel: ^2.0
            pest-plugin-arch: ^2.0
            pest-plugin-livewire: ^2.1
            collision: ^7.0
            stability: prefer-lowest

          - os: ubuntu-latest
            php: 8.1
            laravel: 10.*
            livewire: ^3.0
            testbench: 8.*
            carbon: ^2.63
            pest: ^2.0
            pest-plugin-laravel: ^2.0
            pest-plugin-arch: ^2.0
            pest-plugin-livewire: ^2.1
            collision: ^7.0
            stability: prefer-stable

          - os: ubuntu-latest
            php: 8.2
            laravel: 10.*
            livewire: ^3.0
            testbench: 8.*
            carbon: ^2.63
            pest: ^2.0
            pest-plugin-laravel: ^2.0
            pest-plugin-arch: ^2.0
            pest-plugin-livewire: ^2.1
            collision: ^7.0
            stability: prefer-lowest

          - os: ubuntu-latest
            php: 8.2
            laravel: 10.*
            livewire: ^3.0
            testbench: 8.*
            carbon: ^2.63
            pest: ^2.0
            pest-plugin-laravel: ^2.0
            pest-plugin-arch: ^2.0
            pest-plugin-livewire: ^2.1
            collision: ^7.0
            stability: prefer-stable

          # Laravel 11
          - os: ubuntu-latest
            php: 8.2
            laravel: 11.*
            livewire: ^3.3.5
            testbench: 9.*
            carbon: ^2.63
            pest: ^2.0
            pest-plugin-laravel: ^2.0
            pest-plugin-arch: ^2.0
            pest-plugin-livewire: ^2.1
            collision: ^11.0
            stability: prefer-lowest

          - os: ubuntu-latest
            php: 8.2
            laravel: 11.*
            livewire: ^3.3.5
            testbench: 9.*
            carbon: ^2.63
            pest: ^2.0
            pest-plugin-laravel: ^2.0
            pest-plugin-arch: ^2.0
            pest-plugin-livewire: ^2.1
            collision: ^11.0
            stability: prefer-stable

          # Laravel 12
          - os: ubuntu-latest
            php: 8.2
            laravel: 12.*
            livewire: ^3.5.20
            testbench: 10.*
            carbon: ^3.0
            pest: ^3.7
            pest-plugin-laravel: ^3.1.0
            pest-plugin-arch: ^3.1
            pest-plugin-livewire: ^3.0.0
            collision: ^8.0
            stability: prefer-lowest

          - os: ubuntu-latest
            php: 8.2
            laravel: 12.*
            livewire: ^3.5.20
            testbench: 10.*
            carbon: ^3.0
            pest: ^3.7
            pest-plugin-laravel: ^3.1.0
            pest-plugin-arch: ^3.1
            pest-plugin-livewire: ^3.0.0
            collision: ^8.0
            stability: prefer-stable

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require \
            "livewire/livewire:${{ matrix.livewire }}" \
            --no-interaction --no-update

          composer require \
            "laravel/framework:${{ matrix.laravel }}" \
            "orchestra/testbench:${{ matrix.testbench }}" \
            "nesbot/carbon:${{ matrix.carbon }}" \
            "pestphp/pest:${{ matrix.pest }}" \
            "pestphp/pest-plugin-laravel:${{ matrix.pest-plugin-laravel }}" \
            "pestphp/pest-plugin-arch:${{ matrix.pest-plugin-arch }}" \
            "pestphp/pest-plugin-livewire:${{ matrix.pest-plugin-livewire }}" \
            "nunomaduro/collision:${{ matrix.collision }}" \
            --dev --no-interaction --no-update

          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_HOST: 127.0.0.1 # localhost does not work on some systems
          DB_USERNAME: root
          DB_PASSWORD: ""
          DB_DATABASE: ci_test
        run: composer test-ci

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
